version: '3.8'

services:
  script-runner:
    build: .
    container_name: script-runner
    ports:
      - "8000:8000"
    volumes:
      - ./scripts:/scripts:ro
      - ./app:/app
    environment:
      - SCRIPT_DIR=/scripts
    restart: unless-stopped
